apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flink-ingress
  namespace: streaming-processing 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: flink.ta.vn 
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: flink-sentiment-job-rest
            port:
              number: 8081