auth:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: c2c_trade
  postgresPassword: rootpw


  # Test if the default SA in orchestration can create pods in storage
# kubectl auth can-i create pods -n storage \
#   --as=system:serviceaccount:orchestration:default

# kubectl auth can-i delete pods -n storage \
#   --as=system:serviceaccount:orchestration:default

# kubectl auth can-i get pods -n storage \
#   --as=system:serviceaccount:orchestration:default


# Role binding
kubectl create rolebinding airflow-storage-access \
  --namespace storage \
  --clusterrole edit \
  --serviceaccount=orchestration:default